"""Initial migration.

Revision ID: 798b14cfca83
Revises: 
Create Date: 2021-11-04 15:14:11.124195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '798b14cfca83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Firstname', sa.String(length=45), nullable=False),
    sa.Column('Lastname', sa.String(length=45), nullable=False),
    sa.Column('properties', sa.String(length=45), nullable=True),
    sa.Column('authorization', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classId', sa.Integer(), nullable=True),
    sa.Column('StartDateTime', mysql.DATETIME(), nullable=True),
    sa.Column('ENDDateTime', mysql.DATETIME(), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['Class.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    op.drop_table('User')
    op.drop_table('Class')
    # ### end Alembic commands ###
